### ISSUE TITLE
5 to 1 level change is only partly done

### ISSUE THREAD

**Issue by stronny** [neilbrown/mdadm#13]
root@rescue ~ # cat /proc/mdstat
Personalities : [raid1] [raid6] [raid5] [raid4]
md1 : active raid5 sda2[0] sdb2[1]
      104857600 blocks super 1.2 level 5, 64k chunk, algorithm 2 [2/2] [UU]
root@rescue ~ # mdadm --grow /dev/md1 --level 1
mdadm: Impossible level change requested

Now, looking at Grow.c I can first see checks from current level to a new level, which seem to pass just fine. But then it switches over the new level again, and there is no case for level 1: https://github.com/neilbrown/mdadm/blob/master/Grow.c#L1317-L1410

Am I missing something here?

**Comment by stronny** [comment]
Oh, my bad, it should return and skip the second switch. Now I have no idea at all why it doesn't work.

**Comment by stronny** [comment]
Well, I think I was just being tired. Of course it was a trivial syntax error, should have been `--level=1`. So to be at least somewhat constructive here, I propose a check to be implemented so that mdadm would explicitely tell the user about an invalid RAID level as well as about a missing argument's value that is mandatory.

**Comment by neilbrown** [comment]
No, "--level 1" should work the same as "--level=1".  
I just tested raid5->raid1 conversion and it worked as expected.
What version of mdadm was running on that rescue disk? If it was 3.0 or earlier, that would explain it.

**Comment by stronny** [comment]
3.2.5

**Comment by neilbrown** [comment]
Yes - it doesn't work in 3.2.56 does it.  Hmmm..  Ah, it was fixed by 6a67848ab6dc389634673fda3ec867539a763f38 in mdadm-3.3.
So: all fixed now.
