### ISSUE TITLE
testing raid disk

### ISSUE THREAD

**Issue by f1-outsourcing** [neilbrown/mdadm#15]
I wondered if there is a way to test the write speed of a harddrive member of a online raid device? Goal is to identify the worst performing drive to replace it.

We recently bought some drives and they have some problems. What i noticed is eg. that the write speed of a drive was 6MB/s. 
I know this could be difficult because of the filesystem,lvm,drbd that is on this raid device and mdadm does not know about this. But one can think of reserving some area's on the drives at initialization, that can be used for such tests.

For now i am running tests on a partition at the end of the drive, but i am not satisfied testing like this.

**Comment by neilbrown** [comment]
Please ask general questions about Linux RAID on linux-raid@vger.kernel.org (you can post without subscribing).
