### ISSUE TITLE
assemble on other server

### ISSUE THREAD

**Issue by Alukardd** [neilbrown/mdadm#9]
Hello.

I found strange issue with strange function ```static int name_matches``` in [Assemble.c](https://github.com/neilbrown/mdadm/blob/master/Assemble.c#L28).
We assemble md arrays from imported over SRP LVs. Prior, all our machines have hostnames like xenXX, but now we rename it to cnXX. And... we found this issue.
Why you check only length of hostname, why not check if current ```hostname``` equal to ```homehost``` of the assembling array.

I know that I could create array without ```homehost``` at all. But we don't know about this problem before now.

We thought and decided that for us this code is unnecessary, but we don't avoid it completely. I deal the next:
```c
diff --git a/Assemble.c b/Assemble.c
index cdcdb0f..aac4618 100644
--- a/Assemble.c
+++ b/Assemble.c
@@ -38,8 +38,8 @@ static int name_matches(char *found, char *required, char *homehost)
 		return 1;
 	if (homehost) {
 		int l = strlen(homehost);
-		if (l < 32 && fnd[l] == ':' &&
-		    strcmp(fnd+l+1, required)==0)
+		if (l < 32 &&
+		    strcmp(fnd+(int)(strchr(fnd, ':')-fnd+1), required)==0)
 			return 1;
 	}
 	return 0;
```

**Comment by neilbrown** [comment]
Yes, that function is a bit careless.. it really should be comparing
the homehost name too (Which isn't what you would want).

If you assemble array with
   --name=hostname:arrayname

it will check the name you give rather than the name of the current
host.

The next version of mdadm (to be released soon) will allow you to
create an array with "--homehost=any" so it can easily be assembled on
any host, or to assemble arrays with "--homehost=any" so it won't matter
what host the array was assembled on.

NeilBrown

**Comment by Alukardd** [comment]
> If you assemble array with
>    --name=hostname:arrayname

I know, but it's not preferable way for our scripts. We want detect ```homehost``` from metadata and set it in each assemble command. That is the reason I create this patch.

> --homehost=any

And what difference with ```--homehost=none```?

**Comment by Alukardd** [comment]
Do you plan to add option for ```assemble``` like ```--ignore-homehost```?

**Comment by Alukardd** [comment]
Hello.
Can you explain me current situation?
I can't completely understand commit [86b77d](https://github.com/neilbrown/mdadm/commit/86b77ddf87ee364c1092ae50c8efbd7fa71d5c34).

If I have existing array with valid `homehost` (e.g. `srv01`), how should I assemble it on `srv02` to ignore `homehost` at all?
 - option `--homehost='<ignore>'`

- option `--homehost='any'`

- line in config `HOMEHOST='<ignore>`'

**Comment by neilbrown** [comment]
On Mon, 03 Aug 2015 08:58:08 -0700 Alukardd <notifications@github.com>
wrote:

> Hello.
> Can you explain me current situation?
> I can't completely understand commit [86b77d](https://github.com/neilbrown/mdadm/commit/86b77ddf87ee364c1092ae50c8efbd7fa71d5c34).
> 
> If I have existing array with valid `homehost` (e.g. `srv01`), how should I assemble it on `srv02` to ignore `homehost` at all?
>  - option `--homehost='<ignore>'`
> 
> - option `--homehost='any'`
> 
> - line in config `HOMEHOST='<ignore>`'
> 
Any of those three should work.

NeilBrown
